dry-run by default, fixing with -f

diff --git a/bin/sabre-cs-fixer b/bin/sabre-cs-fixer
--- a/bin/sabre-cs-fixer
+++ b/bin/sabre-cs-fixer
@@ -18,4 +18,20 @@ do
 done
 DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 
-$DIR/php-cs-fixer fix --config-file $DIR/php-cs-fixer-config.php --diff --dry-run .
+#
+# Options
+#
+DRYRUN="--dry-run"
+while getopts ":f" opt; do
+  case $opt in
+    f)
+      DRYRUN=""
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
+done
+
+$DIR/php-cs-fixer fix --config-file $DIR/php-cs-fixer-config.php --diff $DRYRUN .
